# Numpy Arrays 

In [1]:
my_list=[1,2,3,4]

In [3]:
import numpy as np
##1-D array
np.array(my_list)

array([1, 2, 3, 4])

In [7]:
##2-D array
my_li=[[1,2,3,4],[5,6,7,8],[87,88,91,2]]

In [8]:
np.array(my_li)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [87, 88, 91,  2]])

In [13]:
np.arange(0,40,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.random.rand(6)

array([0.36943162, 0.9310036 , 0.66373057, 0.39982199, 0.22224997,
       0.74489465])

In [24]:
np.random.randn(4,4)

array([[-0.99453858, -1.15475042,  1.59792134, -0.25104385],
       [-2.3784054 ,  0.16049825, -0.54998543, -1.93785381],
       [ 0.00280471,  0.6578738 , -0.54866084,  0.7612596 ],
       [-0.38995577,  0.15179209,  0.49747982,  1.2744969 ]])

In [27]:
np.random.randint(1,100,12)

array([58, 81, 90, 28, 91, 19, 25, 30, 89,  6, 34, 43])

In [30]:
my_li

[[1, 2, 3, 4], [5, 6, 7, 8], [87, 88, 91, 2]]

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([19, 13,  0, 37, 45, 18, 13, 47, 10, 42])

In [39]:
my_li.reshape(4,4)

AttributeError: 'list' object has no attribute 'reshape'

In [42]:
ranarr.max()

47

In [43]:
ranarr.min()

0

In [44]:
ranarr

array([19, 13,  0, 37, 45, 18, 13, 47, 10, 42])

In [46]:
ranarr.argmax()

7

In [47]:
ranarr.argmin()

2

# Numpy indexing and selection 

In [52]:
arr=np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
arr[12]

12

In [54]:
##Left side before the : is starting index and after the : is ending index
arr[1:5]

array([1, 2, 3, 4])

In [56]:
##It indicates beyond 4 to all remaining values displays but it doesn't shows before values
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
slice_of_arr =arr[0:6]

In [58]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_of_arr[:]=100

In [60]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [61]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [63]:
arr_2d=np.array([[10,20,30],[5,15,25],[35,45,55]])
arr_2d

array([[10, 20, 30],
       [ 5, 15, 25],
       [35, 45, 55]])

In [64]:
arr_2d[1]

array([ 5, 15, 25])

In [66]:
arr_2d[1,2]

25

In [69]:
arr_2d[:1]

array([[10, 20, 30]])

In [71]:
arr = np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
bool_arr=arr > 6
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [74]:
arr[bool_arr]

array([ 7,  8,  9, 10, 11])

In [75]:
arr[arr<5]

array([1, 2, 3, 4])

In [77]:
arr_2d= np.arange(50).reshape(5,10)

In [78]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arr_2d[2:4,2:5]

array([[22, 23, 24],
       [32, 33, 34]])

# Numpy operations

Array with array....
array with scalars...
Universal array functions.

In [81]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [82]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [83]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])

In [85]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [86]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479])

In [87]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [88]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527])

In [91]:
np.max(arr)

11

In [92]:
##create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [93]:
##create an array of 10  fives
np.zeros(10)+5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [94]:
##create an array of the integers from 10 to 50
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [95]:
##create an array of all the even nnumbers the integers from 10 to 50
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [97]:
## create a 3*3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
## create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
## Random no. b/w 0 and 1
np.random.rand(1)

array([0.17032027])

In [104]:
##Generate an array of 25 random no samplied from a standard normal distribution
np.random.randn(25)

array([-0.2986115 , -1.97668359,  1.13871703, -0.48466607, -1.24861828,
        0.04941936, -2.44496514, -0.24032074,  0.53708249, -1.08083592,
       -1.69972747, -0.30094683,  1.82502672,  1.40839898,  0.53237286,
        0.40382742,  0.39325444, -1.59091272,  0.94551335, -0.27597894,
       -1.38214096, -0.65573162,  0.25283786, -0.48990008, -0.18318951])

In [105]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [106]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [108]:
##20 linear spaced points b/w 0 &1
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [110]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [114]:
## point 20 in mat dataframe
mat[3,4]

20

In [117]:
## point 2,7,12 in mat data frame
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [118]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [122]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
mat.sum()

325

In [125]:
## Get the standard deviation of the values in mat
mat.std()

7.211102550927978

In [126]:
## Get the sum of all columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])